const usuarios = [
    {
        id: 1,
        name: 'Robert Aron Zimmermann',
        genero: 'Masculino',
        linkImagem: 'https://github.com/RA4Z.png',
        cargo: 'Professor',
        estado: 'Santa Catarina',
        cidade: 'Schroeder',
        pais: 'Brasil',
        imcAtual: 26.9,
        seguindo: 24,
        seguidores: 200,
        entrada: '27/06/2023',
        nascimento: '31/07/2003',
        premium: true
    },
    {
        id: 2,
        name: 'Karoline da Rosa de Morais',
        genero: 'Feminino',
        linkImagem: '',
        cargo: 'Aluno',
        estado: 'Santa Catarina',
        cidade: 'Itajaí',
        pais: 'Argentina',
        imcAtual: 22.9,
        seguindo: 3,
        seguidores: 2000,
        entrada: '26/06/2023',
        nascimento: '12/08/2002',
        premium: true
    },
    {
        id: 3,
        name: 'Marcio Zimmermann',
        genero: 'Masculino',
        linkImagem: '',
        cargo: 'Aluno',
        estado: 'Rio Grande do Sul',
        cidade: 'Porto Alegre',
        pais: 'Rússia',
        imcAtual: 30.9,
        seguindo: 5,
        seguidores: 32,
        entrada: '25/06/2023',
        nascimento: '25/06/1981',
        premium: false
    },
    {
        id: 4,
        name: 'Cleuza Liskoski Zimmermann',
        genero: 'Feminino',
        linkImagem: '',
        cargo: 'Professor',
        estado: 'Santa Catarina',
        cidade: 'Jaraguá do Sul',
        pais: 'EUA',
        imcAtual: 22.9,
        seguindo: 254,
        seguidores: 524,
        entrada: '28/06/2023',
        nascimento: '09/08/1981',
        premium: false
    },
  ]
  export { usuarios }