const usuarios = [
    {
        id: 1,
        name: 'Robert Aron Zimmermann',
        email: 'rraz639@gmail.com',
        genero: 'Masculino',
        linkImagem: 'https://github.com/RA4Z.png',
        cargo: 'Professor',
        estado: 'Santa Catarina',
        cidade: 'Schroeder',
        pais: 'Brasil',
        imcAtual: 26.9,
        seguindo: 24,
        seguidores: 200,
        nota: 2,
        entrada: '27/06/2023',
        nascimento: '31/07/2003',
        personal: 0,
        alunos: 36,
        premium: true
    },
    {
        id: 2,
        name: 'Karoline da Rosa de Morais',
        email: 'karol@gmail.com',
        genero: 'Feminino',
        linkImagem: '',
        cargo: 'Aluno',
        estado: 'Santa Catarina',
        cidade: 'Itajaí',
        pais: 'Brasil',
        imcAtual: 22.9,
        seguindo: 3,
        seguidores: 2000,
        nota: 5,
        entrada: '26/06/2023',
        nascimento: '12/08/2002',
        personal: 1,
        alunos: 0,
        premium: true
    },
    {
        id: 3,
        name: 'Marcio Zimmermann',
        email: 'marcio@gmail.com',
        genero: 'Masculino',
        linkImagem: '',
        cargo: 'Aluno',
        estado: 'Rio Grande do Sul',
        cidade: 'Porto Alegre',
        pais: 'Brasil',
        imcAtual: 30.9,
        seguindo: 5,
        seguidores: 32,
        nota: 3,
        entrada: '25/06/2023',
        nascimento: '25/06/1981',
        personal: 4,
        alunos: 0,
        premium: false
    },
    {
        id: 4,
        name: 'Cleuza Liskoski Zimmermann',
        email: 'cleuza@gmail.com',
        genero: 'Feminino',
        linkImagem: '',
        cargo: 'Professor',
        estado: 'Santa Catarina',
        cidade: 'Jaraguá do Sul',
        pais: 'Brasil',
        imcAtual: 22.9,
        seguindo: 254,
        seguidores: 524,
        nota: 4,
        entrada: '28/06/2023',
        nascimento: '09/08/1981',
        personal: 1,
        alunos: 53,
        premium: false
    },
  ]
  export { usuarios }